Cards = {
    ['ALPH1_EN001_LAYLA_HART'] = {
        id = 'ALPH1_EN001_LAYLA_HART',
        name = 'Layla Hart',
        rarity = 'SECRET',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 30',
        effectTitle = 'PINK POWER',
        effectText = 'Every \'Pink\' card on the field boosts this cards ATK by +10',
        setCode = 'ALPH1-EN001',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN001_LAYLA_HART.png'
    },

    ['ALPH1_EN002_MR_BSTAR'] = {
        id = 'ALPH1_EN002_MR_BSTAR',
        name = 'Mr Bstar',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 10',
        defense = 'DEF: 20',
        effectTitle = 'EFFECT',
        effectText = 'Lose 10 HP and draw 2 cards.',
        setCode = 'ALPH1-EN002',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN002_MR_BSTAR.png'
    },

    ['ALPH1_EN003_MAX_TURNER_RILEY'] = {
        id = 'ALPH1_EN003_MAX_TURNER_RILEY',
        name = 'Max Turner Riley',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'Ammo South owner',
        level = 'LEVEL 2',
        speed = 'SPD: 5',
        attack = 'ATK: 40',
        defense = 'DEF: 30',
        effectTitle = 'EFFECT',
        effectText = 'Add 1 \'Ammunation\' card from your deck.',
        setCode = 'ALPH1-EN003',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN003_MAX_TURNER_RILEY.png'
    },

    ['ALPH1_EN004_WYATT_RILEY'] = {
        id = 'ALPH1_EN004_WYATT_RILEY',
        name = 'Wyatt Riley',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'Mirror Park Auto Owner',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 30',
        defense = 'DEF: 40',
        effectTitle = 'EFFECT',
        effectText = 'Add 1 \'Mirror Park Auto\' card from your deck.',
        setCode = 'ALPH1-EN004',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN004_WYATT_RILEY.png'
    },

    ['ALPH1_EN005_XENA_COUGAR_MIRANOVA'] = {
        id = 'ALPH1_EN005_XENA_COUGAR_MIRANOVA',
        name = 'Xena "Cougar" Miranova',
        rarity = 'SUPER',
        type = 'Fighter',
        job = 'SOSMC',
        level = 'LEVEL 2',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 50',
        effectTitle = 'WHITE SHORTS',
        effectText = 'You can use only one of these effects per turn: 1) Swap this card for a \'Cougar\' card from your deck. 2) If you have a \'Cougar\' on the field, swap it for this card from the deck.',
        setCode = 'ALPH1-EN005',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN005_XENA_COUGAR_MIRANOVA.png'
    },

    ['ALPH1_EN006_UNKNOWN_YET'] = {
        id = 'ALPH1_EN006_UNKNOWN_YET',
        name = 'unknown yet',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'SAST',
        level = 'LEVEL 2',
        speed = 'SPD: 2',
        attack = 'ATK: 30',
        defense = 'DEF: 20',
        effectTitle = 'STOP AND SEARCH',
        effectText = 'Your opponent must discard any \'Contraband\' cards in their hand. This effect can only be used once per game.',
        setCode = 'ALPH1-EN006',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN006_UNKNOWN_YET.png'
    },

    ['ALPH1_EN007_BROCK_LEE'] = {
        id = 'ALPH1_EN007_BROCK_LEE',
        name = 'Brock Lee',
        rarity = 'SUPER',
        type = 'Fighter',
        job = 'PDM',
        level = 'LEVEL 2',
        speed = 'SPD: 3',
        attack = 'ATK: 20',
        defense = 'DEF: 30',
        effectTitle = 'EFFECT',
        effectText = 'Equip 1 Vehicle card from your deck to a fighter on the field.',
        setCode = 'ALPH1-EN007',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN007_BROCK_LEE.png'
    },

    ['ALPH1_EN008_HAPPY'] = {
        id = 'ALPH1_EN008_HAPPY',
        name = 'Happy',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 10',
        defense = 'DEF: 30',
        effectTitle = 'CHARIZARDING',
        effectText = 'All \'Fine Shiiiits\' lose all DEF.',
        setCode = 'ALPH1-EN008',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN008_HAPPY.png'
    },

    ['ALPH1_EN009_HIROSHI_YAMATO'] = {
        id = 'ALPH1_EN009_HIROSHI_YAMATO',
        name = 'Hiroshi Yamato',
        rarity = 'RARE',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 20',
        defense = 'DEF: 20',
        effectTitle = 'KAZOKU',
        effectText = 'Gains +10 ATK and DEF for all \'Yamato\' cards you control.',
        setCode = 'ALPH1-EN009',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN009_HIROSHI_YAMATO.png'
    },

    ['ALPH1_EN010_ZOE_MIRANOVA'] = {
        id = 'ALPH1_EN010_ZOE_MIRANOVA',
        name = 'Zoe Miranova',
        rarity = 'SECRET',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 5',
        attack = 'ATK: 40',
        defense = 'DEF: 10',
        effectTitle = 'NO ZOEY, NO!',
        effectText = 'Steal your opponents shoes! All opponents fighters lose 15 DEF.',
        setCode = 'ALPH1-EN010',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN010_ZOE_MIRANOVA.png'
    },

    ['ALPH1_EN011_NIKOLAS_HAAJA'] = {
        id = 'ALPH1_EN011_NIKOLAS_HAAJA',
        name = 'Nikolas Haaja',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'Taxi Co. owner',
        level = 'LEVEL 2',
        speed = 'SPD: 2',
        attack = 'ATK: 10',
        defense = 'DEF: 40',
        effectTitle = 'WHERE CAN I TAKE YA?',
        effectText = 'Add any Location card from your deck.',
        setCode = 'ALPH1-EN011',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN011_NIKOLAS_HAAJA.png'
    },

    ['ALPH1_EN012_D_J'] = {
        id = 'ALPH1_EN012_D_J',
        name = 'D.J',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 20',
        effectTitle = '',
        effectText = '',
        setCode = 'ALPH1-EN012',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN012_D.J.png'
    },

    ['ALPH1_EN013_COUGAR'] = {
        id = 'ALPH1_EN013_COUGAR',
        name = 'Cougar',
        rarity = 'RARE',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 5',
        attack = 'ATK: 50',
        defense = 'DEF: 30',
        effectTitle = 'POACHED',
        effectText = 'If this card is killed in battle, summon 1 \'USFW\' card from your deck or hand.',
        setCode = 'ALPH1-EN013',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN013_COUGAR.png'
    },

    ['ALPH1_EN014_LAYLA_HART'] = {
        id = 'ALPH1_EN014_LAYLA_HART',
        name = 'Layla Hart',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Hardcore Comics owner',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 30',
        defense = 'DEF: 40',
        effectTitle = 'YOUR PACK IS IN THE TRAY!',
        effectText = 'Draw 3 cards, then discard 1.',
        setCode = 'ALPH1-EN014',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN014_LAYLA_HART.png'
    },

    ['ALPH1_EN015_ZACK_GATOR'] = {
        id = 'ALPH1_EN015_ZACK_GATOR',
        name = 'Zack Gator',
        rarity = 'COMMON',
        type = 'Fighter',
        job = 'USFW',
        level = 'LEVEL 2',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 30',
        effectTitle = 'HE PROTECC',
        effectText = 'All animal cards you control gain    +30 DEF.',
        setCode = 'ALPH1-EN015',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN015_ZACK_GATOR.png'
    },

    ['ALPH1_EN016_HAO_YAMATO'] = {
        id = 'ALPH1_EN016_HAO_YAMATO',
        name = 'Hao Yamato',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 10',
        defense = 'DEF: 30',
        effectTitle = 'YAMATO CAMPAIGN',
        effectText = 'Any \'Paleto\' or \'Roxwood\' cards you control cannot be destroyed.',
        setCode = 'ALPH1-EN016',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN016_HAO_YAMATO.png'
    },

    ['ALPH1_EN017_SEN_GANBE'] = {
        id = 'ALPH1_EN017_SEN_GANBE',
        name = 'Sen Ganbe',
        rarity = 'RARE',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 4',
        attack = 'ATK: 30',
        defense = 'DEF: 10',
        effectTitle = 'CAN\'T CATCH ME',
        effectText = 'This card is always treated as a \'Yamato\' card. If this card is attacked, flip a coin. If heads, negate the attack.',
        setCode = 'ALPH1-EN017',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN017_SEN_GANBE.png'
    },

    ['ALPH1_EN018_KENCHIE'] = {
        id = 'ALPH1_EN018_KENCHIE',
        name = 'Kenchie',
        rarity = 'COMMON',
        type = 'Fighter',
        job = 'Wizard',
        level = 'LEVEL 2',
        speed = 'SPD: 3',
        attack = 'ATK: 50',
        defense = 'DEF: 40',
        effectTitle = 'ABRA KADABUNNY?',
        effectText = 'Target 1 \'Fighter\' card, swap it out for any \'Animal\' card of your choosing.',
        setCode = 'ALPH1-EN018',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN018_KENCHIE.png'
    },

    ['ALPH1_EN019_KENCHIE'] = {
        id = 'ALPH1_EN019_KENCHIE',
        name = 'Kenchie',
        rarity = 'SUPER',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 20',
        effectTitle = 'YOU\'RE HIRED!',
        effectText = 'Add 1 \'Promotion\' card from your deck.',
        setCode = 'ALPH1-EN019',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN019_KENCHIE.png'
    },

    ['ALPH1_EN020_NIKOLAS_HAAJA'] = {
        id = 'ALPH1_EN020_NIKOLAS_HAAJA',
        name = 'Nikolas Haaja',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 10',
        defense = 'DEF: 20',
        effectTitle = 'EFFECT',
        effectText = 'After 2 turns, promote this card to a level 2 \'Nikolas\' card from your deck.',
        setCode = 'ALPH1-EN020',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN020_NIKOLAS_HAAJA.png'
    },

    ['ALPH1_EN021_MAX_TURNER_RILEY'] = {
        id = 'ALPH1_EN021_MAX_TURNER_RILEY',
        name = 'Max Turner Riley',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 30',
        defense = 'DEF: 20',
        effectTitle = 'BROTHERS',
        effectText = 'If you control \'Wyatt Riley\', you can summon this card from your hand.',
        setCode = 'ALPH1-EN021',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN021_MAX_TURNER_RILEY.png'
    },

    ['ALPH1_EN022_WYATT_RILEY'] = {
        id = 'ALPH1_EN022_WYATT_RILEY',
        name = 'Wyatt Riley',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 20',
        defense = 'DEF: 30',
        effectTitle = 'BROTHERS',
        effectText = 'If you control \'Max Turner Riley\', you can summon this card from your hand.',
        setCode = 'ALPH1-EN022',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN022_WYATT_RILEY.png'
    },

    ['ALPH1_EN023_JAY_MOZZ'] = {
        id = 'ALPH1_EN023_JAY_MOZZ',
        name = 'Jay Mozz',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 30',
        defense = 'DEF: 30',
        effectTitle = 'EFFECT',
        effectText = 'Add 1 \'Donk\' vehicle card to your hand.',
        setCode = 'ALPH1-EN023',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN023_JAY_MOZZ.png'
    },

    ['ALPH1_EN024_XENA_MIRANOVA'] = {
        id = 'ALPH1_EN024_XENA_MIRANOVA',
        name = 'Xena Miranova',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 20',
        defense = 'DEF: 30',
        effectTitle = '',
        effectText = '',
        setCode = 'ALPH1-EN024',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN024_XENA_MIRANOVA.png'
    },

    ['ALPH1_EN025_JAY_MOZZY'] = {
        id = 'ALPH1_EN025_JAY_MOZZY',
        name = 'Jay Mozzy',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'High notes owner',
        level = 'LEVEL 2',
        speed = 'SPD: 1',
        attack = 'ATK: 30',
        defense = 'DEF: 40',
        effectTitle = 'GET BAKED',
        effectText = 'Add 1 \'Doobie\' card to your hand. Also target 1 fighter on the field, reduce its SPD to 1.',
        setCode = 'ALPH1-EN025',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN025_JAY_MOZZY.png'
    },

    ['ALPH1_EN026_MATT_JACKSON'] = {
        id = 'ALPH1_EN026_MATT_JACKSON',
        name = 'Matt Jackson',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 20',
        defense = 'DEF: 20',
        effectTitle = '',
        effectText = '',
        setCode = 'ALPH1-EN026',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN026_MATT_JACKSON.png'
    },

    ['ALPH1_EN027_BROCK_LEE'] = {
        id = 'ALPH1_EN027_BROCK_LEE',
        name = 'Brock Lee',
        rarity = 'RARE',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 1',
        attack = 'ATK: 10',
        defense = 'DEF: 30',
        effectTitle = 'WABBIT',
        effectText = 'Add 1 \'Wabbit Toaster\' card to your hand.',
        setCode = 'ALPH1-EN027',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN027_BROCK_LEE.png'
    },

    ['ALPH1_EN028_WULFRIK_CHAOSBANE'] = {
        id = 'ALPH1_EN028_WULFRIK_CHAOSBANE',
        name = 'Wulfrik Chaosbane',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 20',
        defense = 'DEF: 20',
        effectTitle = 'EFFECT',
        effectText = 'This card takes no damage from \'Crow\' cards.',
        setCode = 'ALPH1-EN028',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN028_WULFRIK_CHAOSBANE.png'
    },

    ['ALPH1_EN029_CROW'] = {
        id = 'ALPH1_EN029_CROW',
        name = 'Crow',
        rarity = 'SUPER',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 6',
        attack = 'ATK: 10',
        defense = 'DEF: 10',
        effectTitle = 'CAW',
        effectText = 'Your opponent must CAW! or they lose the duel.',
        setCode = 'ALPH1-EN029',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN029_CROW.png'
    },

    ['ALPH1_EN030_BOB_HODGES'] = {
        id = 'ALPH1_EN030_BOB_HODGES',
        name = 'Bob Hodges',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 10',
        defense = 'DEF: 30',
        effectTitle = 'NORTHERN KINDA GUY',
        effectText = 'Add 1 \'Paleto\' location card from your deck.',
        setCode = 'ALPH1-EN030',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN030_BOB_HODGES.png'
    },

    ['ALPH1_EN031_BOD_HODGES'] = {
        id = 'ALPH1_EN031_BOD_HODGES',
        name = 'Bod Hodges',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'SAST',
        level = 'LEVEL 2',
        speed = 'SPD: 2',
        attack = 'ATK: 30',
        defense = 'DEF: 40',
        effectTitle = 'BUSH IMMUNITY',
        effectText = 'If you control a \'Bobs Bush\' card, this card cannot be targeted by opponents card effects.',
        setCode = 'ALPH1-EN031',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN031_BOD_HODGES.png'
    },

    ['ALPH1_EN032_YUKA'] = {
        id = 'ALPH1_EN032_YUKA',
        name = 'Yuka',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 4',
        attack = 'ATK: 30',
        defense = 'DEF: 30',
        effectTitle = 'KAZOKU',
        effectText = 'This card is always treated as a \'Yamato\' card.',
        setCode = 'ALPH1-EN032',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN032_YUKA.png'
    },

    ['ALPH1_EN033_YUKA'] = {
        id = 'ALPH1_EN033_YUKA',
        name = 'Yuka',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Diamond Casino Manager',
        level = 'LEVEL 2',
        speed = 'SPD: 5',
        attack = 'ATK: 40',
        defense = 'DEF: 30',
        effectTitle = 'DON\'T TEST ME',
        effectText = 'This card is always treated as a \'Yamato\' card. Roll a 6 sided dice, if 3 or higher, destroy 1 of your opponents cards. If you roll a 1, destroy one of your own cards.',
        setCode = 'ALPH1-EN033',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN033_YUKA.png'
    },

    ['ALPH1_EN034_SEN_GANBE'] = {
        id = 'ALPH1_EN034_SEN_GANBE',
        name = 'Sen Ganbe',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Diamond Resort Manager',
        level = 'LEVEL 2',
        speed = 'SPD: 6',
        attack = 'ATK: 30',
        defense = 'DEF: 40',
        effectTitle = 'RETURN TO SENDER',
        effectText = 'This card is always treated as a \'Yamato\' card. When a \'Casino\' card is attacked, roll a 6 sided dice. If you roll 4 or higher, the attacker is destroyed instead.',
        setCode = 'ALPH1-EN034',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN034_SEN_GANBE.png'
    },

    ['ALPH1_EN035_HIROSHI_YAMATO'] = {
        id = 'ALPH1_EN035_HIROSHI_YAMATO',
        name = 'Hiroshi Yamato',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Diamond Night Club Manager',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 50',
        defense = 'DEF: 20',
        effectTitle = 'UHH I DON\'T THINK SO!',
        effectText = 'When a \'Casino\' location, item or event card is targeted for destruction, flip a coin, if heads the card is not destroyed.',
        setCode = 'ALPH1-EN035',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN035_HIROSHI_YAMATO.png'
    },

    ['ALPH1_EN036_HAO_YAMATO'] = {
        id = 'ALPH1_EN036_HAO_YAMATO',
        name = 'Hao Yamato',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Diamond Casino Director',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 20',
        defense = 'DEF: 50',
        effectTitle = 'ORGANISE',
        effectText = 'Add 1 \'Casino\' card to your hand.',
        setCode = 'ALPH1-EN036',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN036_HAO_YAMATO.png'
    },

    ['ALPH1_EN037_MATTEO_PIAZZA'] = {
        id = 'ALPH1_EN037_MATTEO_PIAZZA',
        name = 'Matteo Piazza',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 20',
        defense = 'DEF: 20',
        effectTitle = '',
        effectText = '',
        setCode = 'ALPH1-EN037',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN037_MATTEO_PIAZZA.png'
    },

    ['ALPH1_EN038_PADDY_SOULJA'] = {
        id = 'ALPH1_EN038_PADDY_SOULJA',
        name = 'Paddy Soulja',
        rarity = 'RARE',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 2',
        attack = 'ATK: 40',
        defense = 'DEF: 20',
        effectTitle = 'HAZE DER U NO',
        effectText = 'This card gains +20 DEF for every \'Weed\' card on the field.',
        setCode = 'ALPH1-EN038',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN038_PADDY_SOULJA.png'
    },

    ['ALPH1_EN039_LUKE_TAYLOR'] = {
        id = 'ALPH1_EN039_LUKE_TAYLOR',
        name = 'Luke Taylor',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 4',
        attack = 'ATK: 30',
        defense = 'DEF: 20',
        effectTitle = 'M.I.C.K.E.Y',
        effectText = 'Your opponent must do a mickey mouse impression, otherwise you gain +30 HP.',
        setCode = 'ALPH1-EN039',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN039_LUKE_TAYLOR.png'
    },

    ['ALPH1_EN040_LUKE_TAYLOR'] = {
        id = 'ALPH1_EN040_LUKE_TAYLOR',
        name = 'Luke Taylor',
        rarity = 'SUPER',
        type = 'Fighter',
        job = 'Union farm owner',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 50',
        defense = 'DEF: 30',
        effectTitle = 'HARVEST',
        effectText = 'Send any plant or animal card to the cemetary, after 2 turns add any item card from your deck.',
        setCode = 'ALPH1-EN040',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN040_LUKE_TAYLOR.png'
    },

    ['ALPH1_EN041_KENCHIE'] = {
        id = 'ALPH1_EN041_KENCHIE',
        name = 'Kenchie',
        rarity = 'ULTRA',
        type = 'Fighter',
        job = 'Weazel News',
        level = 'LEVEL 2',
        speed = 'SPD: 5',
        attack = 'ATK: 30',
        defense = 'DEF: 30',
        effectTitle = 'THIS JUST IN!',
        effectText = 'Target 1 of your opponents fighters. This card gains the effect of the card you targeted for this turn.',
        setCode = 'ALPH1-EN041',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN041_KENCHIE.png'
    },

    ['ALPH1_EN042_MATTEO_PIAZZA'] = {
        id = 'ALPH1_EN042_MATTEO_PIAZZA',
        name = 'Matteo Piazza',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'LSC Mechanic',
        level = 'LEVEL 2',
        speed = 'SPD: 4',
        attack = 'ATK: 40',
        defense = 'DEF: 30',
        effectTitle = 'LOS SNAIL CUSTOMS',
        effectText = 'Add any \'Vehicle Upgrade\' card to your hand. This card then loses -2 SPD.',
        setCode = 'ALPH1-EN042',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN042_MATTEO_PIAZZA.png'
    },

    ['ALPH1_EN043_ZACK_GATOR'] = {
        id = 'ALPH1_EN043_ZACK_GATOR',
        name = 'Zack Gator',
        rarity = 'COMMON',
        type = 'Fighter',
        job = '',
        level = 'LEVEL 1',
        speed = 'SPD: 3',
        attack = 'ATK: 20',
        defense = 'DEF: 30',
        effectTitle = '',
        effectText = '',
        setCode = 'ALPH1-EN043',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN043_ZACK_GATOR.png'
    },

    ['ALPH1_EN044_MATT_JACKSON'] = {
        id = 'ALPH1_EN044_MATT_JACKSON',
        name = 'Matt Jackson',
        rarity = 'RARE',
        type = 'Fighter',
        job = 'Hardcore Comics',
        level = 'LEVEL 2',
        speed = 'SPD: 3',
        attack = 'ATK: 30',
        defense = 'DEF: 50',
        effectTitle = 'MANUFACTURE',
        effectText = 'Discard 1 card, then search 1 \'Backpack\' card from your deck.',
        setCode = 'ALPH1-EN044',
        edition = '1st Edition',
        inventoryImage = 'ALPH1-EN044_MATT_JACKSON.png'
    }
}
